# Generated by Django 5.0.6 on 2024-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('feedback_curriculum', models.TextField()),
                ('feedback_delivery', models.TextField()),
                ('feedback_methods', models.TextField()),
                ('feedback_resources', models.TextField()),
                ('feedback_evaluation', models.TextField()),
                ('feedback_support', models.TextField()),
                ('feedback_overall', models.TextField()),
            ],
        ),
    ]
